import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { hasAdminSession } from "@/features/admin/server/auth";
import { listCallbackRequests } from "@/features/assessment-callback/server/admin";
import { callbackStatuses, callbackStatusLabels, callbackTopics, optionLabel, timeSlots } from "@/features/assessment-callback/domain";

export const metadata: Metadata = { title: "검사 콜백 관리 | Career Direct Korea", robots: { index: false, follow: false } };

export default async function AdminCallbacksPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  if (!(await hasAdminSession())) redirect("/admin/login");
  const selected = (await searchParams).status;
  const requests = await listCallbackRequests(selected);
  const newCount = requests.filter((request) => request.status === "new").length;
  return <main className="min-h-screen bg-cream px-5 py-10 text-navy sm:px-8 sm:py-14"><div className="mx-auto max-w-6xl"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black tracking-[.16em] text-teal">CAREER DIRECT KOREA</p><h1 className="mt-2 text-3xl font-black sm:text-4xl">검사 콜백 관리</h1><p className="mt-2 text-sm text-navy/55">신규 신청 {newCount}건 · 최근 100건</p></div><Link href="/admin/analytics" className="text-sm font-bold text-teal underline">전환 분석 보기</Link></header><nav className="mt-7 flex flex-wrap gap-2"><Link href="/admin/callbacks" className={`rounded-full px-4 py-2 text-sm font-bold ${!selected ? "bg-navy text-white" : "bg-white"}`}>전체</Link>{callbackStatuses.map((status) => <Link key={status} href={`/admin/callbacks?status=${status}`} className={`rounded-full px-4 py-2 text-sm font-bold ${selected === status ? "bg-navy text-white" : "bg-white"}`}>{callbackStatusLabels[status]}</Link>)}</nav><section className="mt-8 overflow-x-auto rounded-2xl border border-navy/10 bg-white"><table className="min-w-[1000px] w-full text-left text-sm"><thead className="bg-navy/[.04] text-xs text-navy/55"><tr>{["신청일", "이름", "연락처", "희망 일정", "상담 주제", "상태"].map((label) => <th key={label} className="px-4 py-3">{label}</th>)}</tr></thead><tbody>{requests.length ? requests.map((request) => <tr key={request.id} className={`border-t border-navy/8 ${request.status === "new" ? "bg-teal/[.06]" : ""}`}><td className="px-4 py-4">{request.createdAt.toLocaleString("ko-KR", { timeZone: "Asia/Seoul" })}</td><td className="px-4 py-4 font-black"><Link href={`/admin/callbacks/${request.id}`} className="text-teal underline">{request.name}</Link></td><td className="px-4 py-4"><div>{request.phone}</div><div className="text-xs text-navy/45">{request.email}</div></td><td className="px-4 py-4">{request.preferredDate}<br /><span className="text-xs text-navy/45">{optionLabel(timeSlots, request.timeSlot)}</span></td><td className="max-w-64 px-4 py-4">{request.topics.map((topic) => optionLabel(callbackTopics, topic)).join(", ")}</td><td className="px-4 py-4"><span className="rounded-full bg-navy/5 px-3 py-1.5 text-xs font-bold">{callbackStatusLabels[request.status as keyof typeof callbackStatusLabels] ?? request.status}</span></td></tr>) : <tr><td colSpan={6} className="px-5 py-16 text-center text-navy/45">조건에 맞는 콜백 신청이 없습니다.</td></tr>}</tbody></table></section></div></main>;
}
